"""add vendor reply to reviews

Revision ID: 514bf21cc2cf
Revises: fa2b50507006
Create Date: 2026-05-20 08:50:40.885651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514bf21cc2cf'
down_revision = 'fa2b50507006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vendor_replied_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('vendor_replied_at')
        batch_op.drop_column('vendor_reply')

    # ### end Alembic commands ###